# Acronime specifice Capitolului 15 SFM (Risc sistemic / Systemic risk)
# format: acronim -> (forma de origine, limba de origine, traducere RO, traducere EN)
#   ex.: 'EVT': ('Extreme Value Theory', 'en', 'teoria valorilor extreme', None)
# OVERRIDE_CH (optional): acronim -> tuplu, sens diferit doar in acest capitol.
EXTRA = {
    'MES': ('Marginal Expected Shortfall', 'en', 'pierderea marginală așteptată în coadă', None),
    'LRMES': ('Long-Run Marginal Expected Shortfall', 'en', 'MES pe termen lung (pierderea într-o criză de șase luni)', None),
    'SRISK': ('Systemic RISK (capital shortfall in a crisis)', 'en', 'deficitul de capital într-o criză', None),
    'ESRB': ('European Systemic Risk Board', 'en', 'Comitetul European pentru Risc Sistemic', None),
    'IMF': ('International Monetary Fund', 'en', 'Fondul Monetar Internațional', None),
    'FSB': ('Financial Stability Board', 'en', 'Consiliul pentru Stabilitate Financiară', None),
    'BNP': ('Banque Nationale de Paris (BNP Paribas)', 'fr', 'grupul bancar francez BNP Paribas', 'the French banking group BNP Paribas'),
    'ING': ('Internationale Nederlanden Groep', 'nl', 'grupul bancar olandez ING', 'the Dutch banking group ING'),
    'HSBC': ('Hongkong and Shanghai Banking Corporation', 'en', 'grupul bancar britanic HSBC', None),
    'AIG': ('American International Group', 'en', 'grupul american de asigurări AIG', None),
    'UBS': ('Union Bank of Switzerland (former name of UBS)', 'en', 'banca elvețiană UBS', None),
    'FINMA': ('Eidgenössische Finanzmarktaufsicht', 'de', 'Autoritatea elvețiană de supraveghere a piețelor financiare', 'the Swiss Financial Market Supervisory Authority'),
    'AT1': ('Additional Tier 1 (capital instruments)', 'en', 'capital suplimentar de nivel 1', None),
    'CET1': ('Common Equity Tier 1 (capital)', 'en', 'capital comun de nivel 1', None),
    'JPM': ('JPMorgan Chase (ticker symbol)', 'en', 'JPMorgan Chase (simbolul de tranzacționare)', None),
    'IFRS': ('International Financial Reporting Standards', 'en', 'Standardele Internaționale de Raportare Financiară', None),
    'DGC': ('Degree of Granger Causality', 'en', 'gradul de cauzalitate Granger', None),
    'FROM': ('FROM others (connectedness received from the other institutions)', 'en', 'conectivitatea primită de la celelalte instituții', None),
    'TO': ('TO others (connectedness transmitted to the other institutions)', 'en', 'conectivitatea transmisă către celelalte instituții', None),
    'NET': ('NET connectedness (TO minus FROM)', 'en', 'conectivitatea netă (TO minus FROM)', None),
    'FRM': ('Financial Risk Meter', 'en', 'indicatorul riscului financiar', None),
    'TENET': ('Tail-Event driven NETwork risk', 'en', 'riscul de rețea condus de evenimentele din coadă', None),
    'CNSM': ('Comitetul Național pentru Supravegherea Macroprudențială', 'ro', None, 'the National Committee for Macroprudential Oversight'),
    'ASF': ('Autoritatea de Supraveghere Financiară', 'ro', None, 'the Financial Supervisory Authority of Romania'),
    'SVB': ('Silicon Valley Bank', 'en', 'banca americană Silicon Valley Bank', None),
    'G-SIB': ('Global Systemically Important Bank', 'en', 'bancă de importanță sistemică globală', None),
    'G-SIBs': ('Global Systemically Important Banks', 'en', 'bănci de importanță sistemică globală', None),
    'O-SII': ('Other Systemically Important Institution', 'en', 'altă instituție de importanță sistemică', None),
    'DCC': ('Dynamic Conditional Correlation', 'en', 'corelație condiționată dinamică', None),
    'NYU': ('New York University', 'en', 'Universitatea din New York', None),
    'BAC': ('Bank of America (ticker symbol)', 'en', 'Bank of America (simbolul de tranzacționare)', None),
    'GS': ('Goldman Sachs (ticker symbol)', 'en', 'Goldman Sachs (simbolul de tranzacționare)', None),
    'MS': ('Morgan Stanley (ticker symbol)', 'en', 'Morgan Stanley (simbolul de tranzacționare)', None),
    'WFC': ('Wells Fargo and Company (ticker symbol)', 'en', 'Wells Fargo (simbolul de tranzacționare)', None),
    'DBK': ('Deutsche Bank (ticker symbol)', 'en', 'Deutsche Bank (simbolul de tranzacționare)', None),
    'SAN': ('Banco Santander (ticker symbol)', 'en', 'Banco Santander (simbolul de tranzacționare)', None),
    'INGA': ('ING Groep (ticker symbol)', 'en', 'ING Groep (simbolul de tranzacționare)', None),
    'HSBA': ('HSBC Holdings (ticker symbol, London)', 'en', 'HSBC Holdings (simbolul de tranzacționare, Londra)', None),
}
OVERRIDE_CH = {}
